{% set name = "types-docutils" %}
{% set version = "0.21.0.20240423" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-docutils-{{ version }}.tar.gz
  sha256: 7716ec6c68b5179b7ba1738cace2f1326e64df9f44b7ab08d9904d32c23fc15f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/docutils-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for docutils
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
