{% set name = "types-docutils" %}
{% set version = "0.22.0.20250822" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 40efebeef8467ae7648a33f3fa6f778bd94d338ca1f4a1c924b206d2f687f60a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  commands:
    - test -f $SP_DIR/docutils-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for docutils
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
