{% set name = "types-docutils" %}
{% set version = "0.21.0.20241005" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-docutils-{{ version }}.tar.gz
  sha256: 48f804a2b50da3a1b1681c4ca1b6184416a6e4129e302d15c44e9d97c59b3365

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/docutils-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for docutils
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
