# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.22.3.20260712"

package:
  name: types-docutils
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/types-docutils/types_docutils-${{ version }}.tar.gz
  sha256: bed54a50136c8e7613c03ee1c51eb958b42754915df83535de356b974ca05877

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - package_contents:
      site_packages:
        - docutils-stubs/__init__.pyi
  - requirements:
      run:
        - docutils
        - mypy
        - python ${{ python_min }}.*
    script:
      - mypy -p docutils

about:
  summary: Typing stubs for docutils
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/types-docutils
  repository: https://github.com/python/typeshed/tree/main/stubs/docutils

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
